name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOTNET_VERSION: '9.0.x'
  CONFIGURATION: 'Release'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration ${{ env.CONFIGURATION }} --no-restore

      - name: Run tests
        run: dotnet test --configuration ${{ env.CONFIGURATION }} --no-build --verbosity normal

      - name: Run code analysis
        run: dotnet format --verify-no-changes --severity warn

      - name: Pack artifacts
        if: github.ref == 'refs/heads/main'
        run: dotnet pack --configuration ${{ env.CONFIGURATION }} --output ./artifacts

      - name: Upload artifacts
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: ./artifacts/*.nupkg